### ISSUE TITLE
Only show related links when relevant

### ISSUE THREAD

**Issue by michho8** [tryRebooting2023/askus#19]
Please do work for this issue in a branch named, "issue-019"

Every response will have a list of article links "related" to the topic. However, this is because each response will also send back three links with the "highest" scores. We only want it if the topic is relevant to the articles. We would need to discuss how to implement this feature and what constitutes it as "related" for the AI model. 

I'm thinking we may need to specify a level of threshold that each article must pass in order to be considered "relevant."

**Comment by jligeral** [comment]
I think this might be related to an issue concerning the AI answering queries that have nothing to do with our intended domain aka UH IT articles. We could try limiting scope in the chat-controller to achieve this

**Comment by michho8** [comment]
Could figure out how to use `describeIndex` in order to filter the results when sending the query to Pinecone. However, will need a detailed discussion of how we want to deem things as "relevant." Will also need an event handler when there is no "response" that fits our conditions.

Can always increase the constant value as our threshold later.
