### ISSUE TITLE
Fix reference links color for light mode

### ISSUE THREAD

**Issue by michho8** [tryRebooting2023/askus#22]
Our light mode will not change the text color of our reference links. Implement the text color toggle for the references link section since it is no longer inside the response.

Dark mode: ![image](https://github.com/tryRebooting2023/askus/assets/89873670/fb4b6768-1965-4441-b025-3c68da5d6404)
Light mode: ![image](https://github.com/tryRebooting2023/askus/assets/89873670/0ad35db0-6fab-4965-8e10-5b59ab938aa5)

**Comment by frances-uy** [comment]
Will be fixed in branch 'issue-014'
