### ISSUE TITLE
Ensure "News" tab links properly

### ISSUE THREAD

**Issue by frances-uy** [tryRebooting2023/askus#28]

**Comment by frances-uy** [comment]
Please do work for this task in a branch called "issue-028". 

Should show news and events, similar to the actual IT site.

**Comment by michho8** [comment]
Want to create a new page that will display a table of alerts. Similar to the [actual IT site.](https://hawaii.edu/its/alerts/)

Would need to make three separate new collections in the MongoDB:

- [ ] planned outages
- [ ] security alerts
- [ ] general notices/announcements

![Image](https://github.com/tryRebooting2023/askus/assets/89873670/8b2d1564-5d7f-4524-b5f5-c049f7323b73)

**Comment by michho8** [comment]
The link for the tab to go to: https://www.hawaii.edu/its/category/news/

Currently unable to click the tab, but able to right-click and open in new tab.
