### ISSUE TITLE
Fix the testcafe-ci tests

### ISSUE THREAD

**Issue by frances-uy** [tryRebooting2023/askus#29]

**Comment by frances-uy** [comment]
Please do work for this task in a branch called "issue-029".

All the testcafe tests must pass in Github.

**Comment by jligeral** [comment]
All ci tests I created passed.

The first test checks to make sure landing page shows up.
The second tests the sign in and sign out functions.
The third tests that the analytics page shows up.
The fourth tests that the tutorial page shows up.
The fifth test check our search function by entering a specified input, submitting it, and then counting that at least one source appears in the chat area to confirm the chat works.
